apiVersion: apps/v1
kind: Deployment
metadata:
  name: provider-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: provider
  template:
    metadata:
      labels:
        app: provider
    spec:
      containers:
        - name: provider
          image: provider-image:v1
          ports:
            - containerPort: 3000
          